[workspace]
members = [
    "serde",
    "serde_derive",
    "serde_derive_internals",
    "test_suite",
]

[patch.crates-io]
serde = { path = "serde" }

[workspace.dependencies]
proc-macro2 = "1.0.74"
quote = "1.0.35"
syn = "2.0.46"
